# Generated by Django 5.1.4 on 2024-12-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_partsmoto_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='moto_type',
            field=models.CharField(choices=[('sport', 'Sport'), ('bigtrail', 'Bigtrail'), ('naked', 'Naked'), ('custom', 'Custom')], default='sport', max_length=50),
        ),
        migrations.AlterField(
            model_name='partsmoto',
            name='part_type',
            field=models.CharField(choices=[('sport', 'Sport'), ('bigtrail', 'Bigtrail'), ('naked', 'Naked'), ('custom', 'Custom')], max_length=50),
        ),
    ]
